name: Github Actions Demo
run-name: ${{github.actor}} is testing
on: [push]
jobs:
  Explore-Github-actions:
    runs-on: ubuntu-latest
    steps:
      - run : echo "My first gitub action. trigerred by ${{github.event_name}} event"