name: "Hello world workflow"

# Triggers workflow when push to master or production branch
on:
  push:
    branches:
      - master
      - production
      - main

jobs:
  hello_word: 
    runs-on: ubuntu-latest
    steps:
        - name: "Print hello world"
          run: echo "hello world"

        - name: "Print date"
          run: echo date
